name: flutter_movies_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  lint: ^2.3.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
